baseURL = "https://www.podcastdrivendev.com/"
languageCode = "en-gb"
title = "Podcast Driven Dev"
theme = "hyde"

[blackfriday]
  extensions = ["hardLineBreak"]

[params]
  themeColor = "theme-base-09"
  layoutReverse = true
  description = "Things a developer does that aren't the code"
  author = "Al McKinlay and Andrew Smillie"