baseURL = "" # TODO: Buy domain
languageCode = "en-gb"
title = "Podcast Driven Development"
theme = "hyde"

[params]
  themeColor = "theme-base-09"
  layoutReverse = true
  description = "Something about PDD" # TODO: Set up description